### ISSUE TITLE
is this still alive?

### ISSUE THREAD

**Issue by yosiasz** [adtsegaye/crawl-for-parallel-corpora#1]
hello @adtsegaye 

Are you still working on amharic corpora? Looking to implement amharic in spaCy and was looking for some good Amharic copora

You have done great work I see!

thanks

**Comment by MarsPanther** [comment]
I am not currently into this kind of thing, all the data is available to the repository bellow.
spaCy sounds good, let me know your progress and we might collaborate.
https://github.com/adtsegaye/Amharic-English-Machine-Translation-Corpus

**Comment by yosiasz** [comment]
Thanks, I have submitted an amharic support in spacy, will let you know progress. Thanks
